# Kubernetes Services for Telegram ML Bot

apiVersion: v1
kind: Service
metadata:
  name: telegram-ml-bot-service
  namespace: telegram-bot
  labels:
    app: telegram-ml-bot
    component: web
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: telegram-ml-bot
    component: web

---
apiVersion: v1
kind: Service
metadata:
  name: telegram-ml-bot-headless
  namespace: telegram-bot
  labels:
    app: telegram-ml-bot
    component: web
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: telegram-ml-bot
    component: web